/*
====================================================================================================
PROJECT: Customer & Product Sales Analysis (2010–2013)
SCRIPT: 03_EXPLORATORY_DATA_ANALYSIS_EDA
PURPOSE: Investigates data distributions, structural integrity, and initial transactional patterns.
====================================================================================================
*/

USE DataWarehouseAnalytics;


=============================
-- Dimensions Exploration
=============================

-- Explore all countries our customer come from.
 SELECT
	DISTINCT Country
 FROM gold.dim_customers;


 -- Explore all categories, Sub categories and Product
 SELECT DISTINCT 
	category, subcategory, product_name
 FROM	
	gold.dim_products
ORDER BY 1,2,3;

=============================
-- Date Exploration
=============================

 -- Find the date of first and last orders 
 SELECT 
	MIN(order_date) AS First_Order_Date,
	MAX(order_date) AS Last_Order_Date
 FROM gold.fact_sales

 -- How many years of sales are available.
  SELECT 
	DATEDIFF(Year, MIN(order_date), MAX(order_date)) AS Years_of_Sales
 FROM gold.fact_sales

 -- find the youngest and the oldest customer
 SELECT 
	MIN(birthdate) AS Oldest_Customer,
	DATEDIFF(Year, MIN(birthdate), GETDATE()) AS Oldest_Customer_Age,
	MAX(birthdate) AS Youngest_Customer,
	DATEDIFF(Year, MAX(birthdate), GETDATE()) AS Youngest_Customer_Age
 FROM gold.dim_customers;

=============================
-- Measure exploration
=============================

 -- Find total sales
 SELECT 
	SUM(sales_amount) AS Total_Sales
 FROM gold.fact_sales;

 -- Find how many Items are Sold
 SELECT
   Count(quantity) AS total_Qty_sold
 FROM gold.fact_sales

 -- Find Average selling price
 SELECT 
  AVG(price) AS Avg_Selling_Price
 FROM gold.fact_sales

 -- Find total numbers of orders
  SELECT 
   Count(order_number) AS total_item_sold,
   Count(DISTINCT order_number) AS total_item_sold
 FROM gold.fact_sales

 -- Find total Number of product
 SELECT 
   Count(product_key) AS total_number_Product,
   Count(DISTINCT product_key) AS total_number_Product 
FROM gold.fact_sales

 -- Find total number of customers
 SELECT 
	COUNT(customer_key) AS Total_Customers
 FROM gold.dim_customers

 -- Find total number of customers that has placed an order
 SELECT 
	COUNT(DISTINCT customer_key) AS Total_ordered_customer,
	COUNT(customer_key) AS Total_ordered_customer
 FROM gold.fact_sales

=============================
-- Magnitude
=============================

 -- Find total customers by countries
 SELECT 
	Country,
 	Count(Customer_key) AS Total_Customers
 FROM
	gold.dim_customers
GROUP BY 
	country
ORDER BY Total_Customers desc;
	
 
 -- Find total customers by gender
 SELECT 
	Gender,
	Count(customer_key) AS Total_Customers
 FROM gold.dim_customers
 GROUP BY Gender
ORDER BY Total_Customers desc;


 -- Find total Product by categories
 SELECT 
	category,
	Count(Product_key) AS Total_Product
 FROM gold.dim_products
 GROUP BY category
 ORDER BY Total_Product DESC;

 -- What are the average cost in each category?
SELECT * FROM gold.dim_products;
SELECT * FROM gold.fact_sales;

SELECT 
	category,
	AVG(cost) AS Avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_costs DESC;


 -- What in the total revenue generated by each category?
 SELECT * FROM gold.dim_products;
SELECT * FROM gold.fact_sales;

SELECT 
	p.category,
	Sum(s.sales_amount) AS Total_Revenue
FROM gold.dim_products p
JOIN gold.fact_sales s ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC;


-- Find total revenue is generated by each customer

SELECT 
	c.Customer_key,
	c.first_name,
	c.last_name,
	Sum(s.sales_amount) AS Total_Revenue
FROM gold.dim_customers c
Left JOIN gold.fact_sales s 
		ON c.customer_key = s.customer_key
GROUP BY 
	c.Customer_key,
	c.first_name,
	c.last_name
ORDER BY Total_Revenue DESC 

-- What is the distribution of items sold across countries?

SELECT 
	c.country,
	Sum(s.quantity) AS Quantity_sold
FROM gold.dim_customers c
Left JOIN gold.fact_sales s 
			ON c.customer_key = s.customer_key
GROUP BY 
	c.country
ORDER BY 
	Quantity_sold DESC

=============================
-- Ranking
=============================


-- Which 5 products generate the highest revenue?

SELECT TOP 5
	p.product_name,
	SUM(s.sales_amount) AS Total_Revenue
FROM gold.dim_products p
Left JOIN gold.fact_sales s 
		ON p.product_key = s.product_key
GROUP BY 
   p.product_name
ORDER BY 
	Total_Revenue DESC


-- What are the 5 Worst performing product in terms of sales?

SELECT TOP 5
	p.product_name,
	SUM(s.sales_amount) AS Total_Revenue
FROM  gold.fact_sales s
Left JOIN  gold.dim_products p
		ON p.product_key = s.product_key
GROUP BY 
   p.product_name
ORDER BY 
	Total_Revenue 


-- Find the top 10 customers who have generated the highest revenue?

SELECT TOP 10
	s.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c 
		ON s.customer_key = c.customer_key
GROUP BY 
	s.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	Total_Revenue DESC


-- Find 3 Customers with the fewest orders placed?

SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS Total_Orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c 
		ON s.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	Total_orders












	

